[package]
name = "datanftmint-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = [ "Ovidiu Damian - Itheum","Bucur David - Itheum"]

[dev-dependencies]

[dependencies.datanftmint]
path = ".."

[dependencies.multiversx-sc]
version = "0.39.7"

[dependencies.multiversx-sc-meta]
version = "0.39.7"
