[package]
name = "datanftmint-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = [ "Ovidiu Damian - Itheum","Bucur David - Itheum"]

[dev-dependencies]

[dependencies.data_market]
path = ".."

[dependencies.multiversx-sc]
version = "0.39.4"

[dependencies.multiversx-sc-meta]
version = "0.39.4"
