[package]
name = "datanftmint-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = [ "Damian Ovidu - Itheum"]

[dev-dependencies]

[dependencies.datanftmint]
path = ".."

[dependencies.elrond-wasm]
version = "0.38.0"

[dependencies.elrond-wasm-modules]
version = "0.38.0"

[dependencies.elrond-wasm-debug]
version = "0.38.0"
