// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           39
// Async Callback:                       1
// Total number of exported functions:  41

#![no_std]
#![feature(alloc_error_handler, lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    datanftmint
    (
        initializeContract
        mint
        burn
        setTreasuryAddress
        setIsPaused
        setAntiSpamTax
        setWhiteListEnabled
        setWhiteListSpots
        removeWhiteListSpots
        setMintTimeLimit
        setRoyaltiesLimits
        setMaxSupply
        setAdministrator
        getTokenId
        getTreasuryAddress
        getMintedTokens
        getAntiSpamTax
        getIsPaused
        getMaxRoyalties
        getMinRoyalties
        getMaxSupply
        getMintedPerAddress
        getContractInitialized
        mintTimeLimit
        lastMintTime
        getWhiteList
        getCollectionFreezedList
        getSftsFreezedForAddress
        getFreezedCount
        isWhiteListEnabled
        getAdministrator
        getUserDataOut
        pause
        unpause
        freeze
        unfreeze
        freezeSingleNFT
        unFreezeSingleNFT
        wipeSingleNFT
        callBack
    )
}
